FROM python:3.11.7

WORKDIR /app

# Install JDK and other necessary tools
RUN apt-get update && apt-get install -y \
    default-jdk \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin


# Set environment variables for jnius
ENV CPPFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux"
ENV LDFLAGS="-L$JAVA_HOME/lib/server"

# Copy requirements file and install dependencies
COPY requirements.txt .

# Install other requirements, excluding jnius
RUN pip install -r requirements.txt 

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Set the command to run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]