version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/12345678
    ports:
      - "7480:7474"
      - "7690:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins

  # ai_service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ai
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - neo4j
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=12345678
  #   command: python ai/ai_fine_tune_neo4j.py

  web_app:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=12345678
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  neo4j_data:
  neo4j_logs: