openapi: 3.0.1
info:
  version: 1.0.0
  title: MusicBud API
  description: A simple API to illustrate Musicbud APIs

servers:
  - url: http://localhost:8000/


paths:

  
  /login:
    get:
      description: login or signup a user  
     
      responses:
        '200':
          description: generated authorization link successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                      code:
                        type: integer
                      status:
                        type: string
                      message:
                        type: string
                      data:
                        type: object
                        properties:
                          authorization_link:
                            type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '422':
          #  ----- Added line  ----------------------------------------
         $ref: '#/components/responses/422Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------
  

  
  /callback:
    get:
      parameters:
        - in: query
          name: code
          schema:
            type: string
      description: generates a token
      responses:
        '200':
          description: logged in successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                
                    code:
                      type: integer
                    successful:
                      type: boolean
                    message:
                      type: string
                    data:
                      type: object
                      properties:
                        accessToken:
                          type: string
                        refreshToken:
                          type: string
                        expiresIn:
                          type: string
          
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '422':
          #  ----- Added line  ----------------------------------------
         $ref: '#/components/responses/422Error'
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'

  /refresh-token:
    post:
      description: refresh token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: get new token.
          content:
            application/json:
              schema:
                type: object
                properties:
                
                    code:
                      type: integer
                    successful:
                      type: boolean
                    message:
                      type: string
                    data:
                      type: object
                      properties:
                        accessToken:
                          type: string
                        refreshToken:
                          type: string
                        expiresIn:
                          type: string      
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '422':
          #  ----- Added line  ----------------------------------------
         $ref: '#/components/responses/422Error'
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
  /get-my-profile:
    post:
      description: View logged user profile
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/navigation'
      responses:
        '200':
          description: Successfully email sent with token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: boolean
                  data:
                    type: object
                    properties:
                      topArtists:
                        type: object
                      topTracks:
                        type: object
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '422':
          #  ----- Added line  ----------------------------------------
         $ref: '#/components/responses/422Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------              
  

  /update-my-likes:
    post:
      description: import user's spotify data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Valid token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  defaultResponse:
                    type: object
                    properties:
                      code:
                        type: integer
                      successful:
                        type: boolean
                      message:
                        type: string
                  data:
                    type: object
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '422':
          #  ----- Added line  ----------------------------------------
         $ref: '#/components/responses/422Error'
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------    
  /set-my-bio:
    post:
      description: set user's bio
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                bio:
                  type: string
     
      responses:
        '200':
          description: Logged out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  defaultResponse:
                    type: object
                    properties:
                      code:
                        type: integer
                      successful:
                        type: boolean
                      message:
                        type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------    

  /get-bud-profile:
    post:
      description: display bud's profile data - artists - tracks - genres
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                bud_id:
                  type: string
     
      responses:
        '200':
          description: Logged out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  defaultResponse:
                    type: object
                    properties:
                      code:
                        type: integer
                      successful:
                        type: boolean
                      message:
                        type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------      
  /get-buds-by-artists:
    post:
      description: returns buds profiles with similar taste in artists 
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/navigation'
           
      responses:
        '200':
          description: "HTTP OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                      code:
                        type: integer
                      status:
                        type: string
                      message:
                        type: string
                      data:
                        type: object
                        properties:
                          authorization_link:
                            type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '422':
          #  ----- Added line  ----------------------------------------
         $ref: '#/components/responses/422Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------
  
  
  /get-buds-by-tracks:
    post:
      description: display buds with similar taste in tracks
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/navigation'
     
      responses:
        '200':
          description: Logged out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  defaultResponse:
                    type: object
                    properties:
                      code:
                        type: integer
                      successful:
                        type: boolean
                      message:
                        type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------  

  /get-buds-by-genres:
    post:
      description: display buds with similar taste in genres
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/navigation'
     
      responses:
        '200':
          description: Logged out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  defaultResponse:
                    type: object
                    properties:
                      code:
                        type: integer
                      successful:
                        type: boolean
                      message:
                        type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------  

  /get-buds-by-artists-and-tracks-and-genres:
    post:
      description: display buds with similar taste in artists and tracks
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/navigation'
     
      responses:
        '200':
          description: Logged out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  defaultResponse:
                    type: object
                    properties:
                      code:
                        type: integer
                      successful:
                        type: boolean
                      message:
                        type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------  


  /search-channels-and-users:
    post:
      description: search server for user's name or channel's name
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Logged out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  defaultResponse:
                    type: object
                    properties:
                      code:
                        type: integer
                      successful:
                        type: boolean
                      message:
                        type: string
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
        '401':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/401Error'
          #  ---- /Added line  ----------------------------------------
        '500':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/500Error'
          #  ---- /Added line  ----------------------------------------  


components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: authorization
      in: header

  #  ----- Added lines  ----------------------------------------
  
  
  schemas:
  
    navigation:
   
      type: object 
      properties:
        skip:
          type: integer
        limit:
          type: integer
          
    Error:
      type: object
      properties:
        code:
          type: integer
        status:
          type: string
        message:
          type: string 
        type: 
          type: string       
        data:
          type: object
        error:
          type: object
          properties:
            msg:
              type: string
    
      
  responses:
    400Error:
      description: Invalid request
      content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  
    422Error:
      description: Unprocessable Entity
      content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    
    500Error:
      description: Internal server error
      content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    401Error:
      description: Not authorized
      content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    404Error:
      description: Error not found
      content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    