# Generated by Django 5.1 on 2024-08-29 04:22

from django.db import migrations

def update_message_model(apps, schema_editor):
    Message = apps.get_model('chat', 'Message')
    for message in Message.objects.all():
        if hasattr(message, 'user'):
            message.author = message.user
            message.save()

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',  # Change this from 'user' to 'author'
            new_name='user',
        ),
        migrations.RunPython(update_message_model),
    ]
