# Generated by Django 5.1 on 2024-08-29 04:28

from django.db import migrations
from django.conf import settings
import django.db.models.deletion

def forward_func(apps, schema_editor):
    Message = apps.get_model('chat', 'Message')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    db_alias = schema_editor.connection.alias
    default_user = User.objects.using(db_alias).first()
    if default_user:
        Message.objects.using(db_alias).update(author=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_update_message_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
