# Generated by Django 5.1 on 2024-08-29 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_user_message_author"),
    ]

    operations = []
