# Generated by Django 5.1 on 2024-08-29 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_message_options_remove_message_channel_and_more"),
    ]

    operations = []
