# Generated by Django 5.1 on 2024-08-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={},
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.channel",
            ),
        ),
    ]
