# Generated by Django 5.0.7 on 2024-08-02 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
