# Generated by Django 5.1 on 2024-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoparentuser",
            name="access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="djangoparentuser",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
